name: Nightly Snapshot

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  snapshot:
    name: Snapshot
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
    - uses: burrunan/gradle-cache-action@v1
      name: Publish Snapshot
      env:
        S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
        S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
        ghNexuUsername: ${{ secrets.NEXUS_USERNAME }}
        ghNexusPassword: ${{ secrets.NEXUS_PASSWORD }}
      with:
        job-id: jdk8
        arguments: publishToNexus  -Pgh -P ghNexuUsername=${{ secrets.NEXUS_USERNAME }}
